### ISSUE TITLE
I encountered a problem when using the plug-in. When I pick up copper or iron or gold, the experience value will not increase, and the console will report an error

### ISSUE THREAD

**Issue by nkxingxh** [notfoundname/XPWars#3]
I encountered a problem when using the plug-in. When I pick up copper or iron or gold, the experience value will not increase, and the console will report an error. The server I use is Paper 1.16.1, and my Java version is 11.

Could not pass event EntityPickupItemEvent to XPWars v1.4
java.lang.NullPointerException: null
        at nfn11.xpwars.listener.XPWarsPlayerListener.onPickup(XPWarsPlayerListener.java:108) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor677.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-131]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-131]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-131]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.EntityItem.pickup(EntityItem.java:380) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.EntityHuman.c(EntityHuman.java:468) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.EntityHuman.movementTick(EntityHuman.java:438) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.EntityLiving.tick(EntityLiving.java:2465) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.EntityHuman.tick(EntityHuman.java:156) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.EntityPlayer.playerTick(EntityPlayer.java:503) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.PlayerConnection.tick(PlayerConnection.java:159) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.NetworkManager.a(NetworkManager.java:373) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.ServerConnection.c(ServerConnection.java:142) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1379) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by notfoundname** [comment]
Thank you! I'm gonna look into it later.

**Comment by notfoundname** [comment]
[XPWars-1.5-SNAPSHOT-null.zip](https://github.com/notfoundname/XPWars/files/5049398/XPWars-1.5-SNAPSHOT-null.zip)
try that build. ignore the update checker warning.

**Comment by nkxingxh** [comment]
I tried, but the problem still exists

**Comment by notfoundname** [comment]
Wait when ScreamingSandals will finish their new repository
