### ISSUE TITLE
Error occurred while enabling SBA v1.5.5 (Is it up to date?)

### ISSUE THREAD

**Issue by TheFloodDragon** [notfoundname/XPWars#4]
[13:54:41] [Server thread/INFO]: [SBA] Disabling SBA v1.5.5
[13:54:41] [Server thread/ERROR]: Failed to initialize the command manager
[13:54:41] [Server thread/INFO]: [SBA] Disabling SBA v1.5.5
[13:54:41] [Server thread/ERROR]: Error occurred while enabling SBA v1.5.5 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register io.github.pronze.sba.service.HealthIndicatorService@5aadb12 while not enabled
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:612) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at io.github.pronze.sba.SBA.registerListener(SBA.java:187) ~[?:?]
        at io.github.pronze.sba.service.HealthIndicatorService.postEnabled(HealthIndicatorService.java:52) ~[?:?]
        at io.github.pronze.sba.SBA_BukkitImpl$5.run(SBA_BukkitImpl.java:141) ~[?:?]
        at io.github.pronze.lib.screaminglib.utils.ControllableImpl.postEnable(ControllableImpl.java:57) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at io.github.pronze.lib.screaminglib.utils.ControllableImpl.postEnable(ControllableImpl.java:55) ~[?:?]
        at io.github.pronze.sba.SBA_BukkitImpl.onEnable(SBA_BukkitImpl.java:431) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at java.lang.Thread.run(Thread.java:834) [?:?]

So is the development version

**Comment by notfoundname** [comment]
https://discord.gg/4xB54Ts
